# Description: Constants for the API

# REQUEST
REQUEST_TYPE_POST = "POST"
REQUEST_TYPE_GET = "GET"
REQUEST_TYPE_EXECUTE = "EXECUTE"

ACTION_START = "start"
ACTION_STOP = "stop"
HOME_ROBOT= "home"
ACTION_RESTART = "restart"
ACTION_CALIBRATE = "calibrate"
ACTION_GET_SETTINGS = "getSettings"
ACTION_SET_SETTINGS = "setSettings"
ACTION_CREATE_WORKPIECE = "createWorkpiece"
ACTION_SAVE_WORKPIECE = "saveWorkpiece"
ACTION_SAVE_WORKPIECE_DXF = "saveWorkpieceDXF"

# CAMERA
CAMERA_ACTION_GET_LATEST_FRAME = "getLatestFrame"
CAMERA_ACTION_RAW_MODE_ON = "rawModeOn"
CAMERA_ACTION_RAW_MODE_OFF = "rawModeOff"

REQUEST_ACTION_CURRENT_POSITION = "currentPosition"

ROBOT_ACTION_SAVE_POINT = "savePoint"

ROBOT_ACTION_JOG_X_MINUS = "jogXMinus"
ROBOT_ACTION_JOG_X_PLUS = "jogXPlus"
ROBOT_ACTION_JOG_Y_MINUS = "jogYMinus"
ROBOT_ACTION_JOG_Y_PLUS = "jogYPlus"
ROBOT_ACTION_JOG_Z_MINUS = "jogZMinus"
ROBOT_ACTION_JOG_Z_PLUS = "jogZPlus"


REQUEST_RESOURCE_ROBOT = "Robot"
REQUEST_RESOURCE_CAMERA = "Camera"
REQUEST_RESOURCE_GLUE_NOZZLE = "glueNozzle"
REQUEST_RESOURCE_WORKPIECE = "workpiece"


# RESPONSE
RESPONSE_STATUS_SUCCESS = "success"
RESPONSE_STATUS_ERROR = "error"
RESPONSE_STATUS_WARNING = "warning"

